### ISSUE TITLE
VAT

### ISSUE THREAD

**Issue by john1821** [OnecodeGr/shopflix-connector-opencart#12]
Any plan to include VAT line items in the **oc_order** and **oc_order_total**?  

Right now the shopflix order comes in as this

![no_vat](https://user-images.githubusercontent.com/100766436/172115969-16871869-e204-49ea-94ea-b8efd2b516e2.png)

a regular OC order appears like this:

![with_vat](https://user-images.githubusercontent.com/100766436/172115993-49638ef1-8dd4-425b-ba12-9b5a7597c6a8.png)

The XML feeds takes into account the product tax_class_id.  The code in the shopflix order ignores it by setting it to zero:

![code](https://user-images.githubusercontent.com/100766436/172116189-33ea13db-e3e7-4294-bdd0-5a9dd8a8f3d9.png)

Thank you.

**Comment by john1821** [comment]
Good day.  Any plan to look into this?  Thank you.

**Comment by spyrmp** [comment]
Hello this is not a problem the values of sub_total and total are from the SHOPFLIX API. 
The ``fineTuneTotals`` function is used to correlate data from SHOPFLIX.
