### ISSUE TITLE
Saved payment method is not shown in configuration

### ISSUE THREAD

**Issue by john1821** [OnecodeGr/shopflix-connector-opencart#5]
Saved payment method is not shown in configuration

admin/view/template/extension/module/onecode/shopflix/config.twig

This line needs to be :

                                    {% if method.id == payment_method %}

![twig](https://user-images.githubusercontent.com/100766436/157428808-3f4986d5-c6f8-4f68-98fb-b92c7bb67af6.png)

**Comment by akondylis** [comment]
fixed on version 1.2.4
