### ISSUE TITLE
VAT

### ISSUE THREAD

**Issue by john1821** [OnecodeGr/shopflix-connector-opencart#8]
I think there is a problem with how the products are saved in the **oc_order_product** table.  

Here is an order, that has a final price of 46,15 (special price of 37,22 + 24% VAT) ... it is shown correctly in shopify vendor BUT the OC order has a different amount even though the order details are correct.  I have included screenshots for your review.

![screenshot 2022-03-14 at 14 58 02](https://user-images.githubusercontent.com/100766436/158177492-f07248f4-f3e5-4db5-ac2b-fdcc7358f635.png)

![screenshot 2022-03-14 at 14 57 55](https://user-images.githubusercontent.com/100766436/158177502-774cd2f5-9257-416e-9b9f-39c37535de04.png)

![screenshot 2022-03-14 at 14 57 23](https://user-images.githubusercontent.com/100766436/158180292-f85b0e80-b52b-4ab1-9acf-2943109d8f74.png)

![screenshot 2022-03-14 at 14 57 05](https://user-images.githubusercontent.com/100766436/158177536-1534aa32-f0c2-4e73-9106-1fccadd20b82.png)

**Comment by akondylis** [comment]
fixed in #v1.2.9
